cmm/main.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Chaosmentors Matchpoint App"""
import os
from flask import request, session
from flask_debugtoolbar import DebugToolbarExtension
from cmm import app
from cmm.views.root import root as root
from cmm.views.user import user as user
from cmm.views.admin import admin as admin
import flask_admin
from flask_admin.contrib.peewee import ModelView

from cmm.models.tag import Tag, HiddenTag
from cmm.models.user import User


@app.babel.localeselector
def get_locale():
    """
    Get the users locale Setting
    """
    if 'lang' in session:
        ret = session['lang']
        session['lang'] = 'de'
    else:
        ret = request.accept_languages.best_match(app.languages.keys())

    #ret = 'en'
    return ret


def setup_db():
    if app.config_obj['main']['create_test_data']:
        from helpers.create_database import create_demo_db
        create_demo_db('../helpers/demodata', truncate=True)


def register_blueprints():
    app.register_blueprint(root, url_prefix="/")
    app.register_blueprint(user, url_prefix="/user")
    app.register_blueprint(admin, url_prefix="/admin")


def setup_admin():
    adm = flask_admin.Admin(app, name='CMM: admin', endpoint='admin')
    adm.add_view(ModelView(User, endpoint='users'))
    adm.add_view(ModelView(Tag, endpoint='tags'))
    adm.add_view(ModelView(HiddenTag, endpoint='hiddentags'))


def run_server():
    """
    Start the Development Server
    """
    print(app.selected_language)
    app.secret_key = app.config_obj['app']['secret_key']
    app.debug = app.config_obj['main']['server_debug']
    DebugToolbarExtension(app)

    setup_db()
    setup_admin()
    register_blueprints()

    app.run(
        host=os.getenv('BIND_IP', app.config_obj['main']['server_ip']),
        port=int(os.getenv('BIND_PORT', app.config_obj['main']['server_port'])))


if __name__ == '__main__':
    run_server()

cmm/views/user.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
""" This is the Module for the User pages.

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.
This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with
this program. If not, see <http://www.gnu.org/licenses/>.
"""
from flask import render_template, Blueprint, request, session, make_response
from flask import current_app as app
from flask_babel import gettext
from unqlite_db import create_user, get_user, get_all_users, get_tags

user = Blueprint('user', __name__, template_folder='templates')


@user.route('/<user_id>')
def page(user_id):
    user_data = get_user(user_id)
    resp = make_response(render_template("user_profile.html", user=user_data))
    resp.set_cookie('user_id', user_id)
    return resp


@user.route('/register')
def register():
    return render_template("user_register.html", tags=get_tags(), c=app.config_obj, title="Register")


@user.route('/response', methods=['POST'])
def register_response():
    nickname = request.form.get("nickname")
    mail = request.form.get("mail")
    description = request.form.get("description")
    chaos_tags = dict()
    for tag in tags:
        if request.form.get(tag):
            chaos_tags[tag] = (request.form.get(tag))
    user_uuid = create_user(nickname, mail, description, chaos_tags)
    return render_template(
        "user_register_response.html",
        name=nickname,
        mail=mail,
        description=description,
        tags=chaos_tags,
        user_uuid=user_uuid,
        c=app.config_obj,
        title="Register Response")

cmm/views/users.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
'''Module for the user Pages'''
from flask import render_template, Blueprint, request, session, make_response
from flask import current_app as app
from flask_babel import gettext
from unqlite_db import create_user, get_user, get_all_users

users = Blueprint('users', __name__, template_folder='templates')

tags = [
    'lockpicking',
    'hacking',
    'soldering',
    'dancing',
    'music'
        ]


@users.route('/<user_id>')
def page(user_id):
    user = get_user(user_id)
    resp = make_response(render_template("users_profile.html", user=user))
    resp.set_cookie('user_id', user_id)
    return resp


@users.route('/register')
def register():
    return render_template("users_register.html", tags=tags, c=app.config_obj, title="Register")


@users.route('/response', methods=['POST'])
def register_response():
    nickname = request.form.get("nickname")
    mail = request.form.get("mail")
    description = request.form.get("description")
    chaos_tags = dict()
    for tag in tags:
        if request.form.get(tag):
            chaos_tags[tag] = (request.form.get(tag))
    user_uuid = create_user(nickname, mail, description, chaos_tags)
    return render_template(
        "users_register_response.html",
        name=nickname,
        mail=mail,
        description=description,
        tags=chaos_tags,
        user_uuid=user_uuid,
        c=app.config_obj,
        title="Register Response")

cmm/templates/admin_user_list.html
{% extends "default/base.html" %}

{% block title %}
 {{c.app.page_title + " " + c.app.version_string + " - " + title}}
{% endblock %}

{% block content %}

<table class="table">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">name</th>
      <th scope="col">Mail</th>
      <th scope="col">Tags</th>
      <th scope="col">Description</th>
    </tr>
  </thead>
  <tbody>
{% for user in users: %}
<tr>
  <td>{{user.id.decode('utf-8')}}</td>
  <td>{{user.name.decode('utf-8')}}</td>
  <td>{{user.mail.decode('utf-8')}}</td>
  <td>{{user.tags.decode('utf-8')}}</td>
  <td>{{user.description.decode('utf-8')}}</td>
</tr>
{% endfor %}
  </tbody>
</table>
{% endblock %}

cmm/templates/admin_xxx.html
{% extends "default/base.html" %}

{% block title %}
 {{c.app.page_title + " " + c.app.version_string + " - " + title}}
{% endblock %}

{% block content %}

<p>admin required</p>

{% endblock %}

cmm/templates/main.html
{% extends "default/base.html" %}

{% block title %}
 {{c.app.page_title + " " + c.app.version_string + " - " + title}}
{% endblock %}

{% block content %}
<br><br>
<div class="jumbotron">
  <center>
    <img src="{{c.event.logo}}"><br>
    <h1 class="display-4">{{c.app.page_title}}</h1>
    <p class="lead">{{ _('Welcome to the matchmaking software of the Chaosmentors')}}</p>
  <hr class="my-4">
  <p>{{_('Demotext')}}
  </p>
  <a class="btn btn-primary btn-lg" href="/users/register" role="button">{{_('Register')}}</a></center>
</div>

  </tbody>
</table>
{% endblock %}

{% block footer %}
<div class="corner-ribbon bottom-right sticky green shadow"><small>We do not Track!</small></div>
{% endblock %}

cmm/templates/register.html
{% extends "default/base.html" %}

{% block title %}
 {{c.app.app_title + " " + c.app.version_string + " - " + title}}
{% endblock %}

{% block content %}
<div class="jumbotron">
    <h3>Please Register as a Mentee</h3>
    <form method="POST" action="{{url_for('api.register_response')}}">

                    <label for="nickname">Nickname:</label>
                    <input type="text" id="nickname" name="nickname" class="form-control" required>


                    <label for="mail">Mail:</label>
                    <input type="email" id="mail" name="mail" class="form-control" required>



                    <label for="description">Description:</label>
                    <textarea
                            rows="5"
                            cols="60"
                            id="description"
                            class="form-control"
                            placeholder="Please give us a brief description of yourself and your interests!">

                    </textarea>


        <br><br>
        <h6>Please select your Interests:</h6>
        {% for tag in tags: %}
        <fieldset id="{{tag}}">



                        <div class="form-col cmm-border-right">
                            <h7>{{tag}}: </h7>
                        </div>
                        <div class="form-col">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="{{tag}}" id="interested" value="interested" checked="checked" />
                                <label for="interested" class="form-check-label">1</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="{{tag}}" id="maybe" value="maybe"/>
                                <label for="maybe" class="form-check-label">2</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="{{tag}}" id="dislike" value="dislike" />
                                 <label for="dislike" class="form-check-label">3</label>
                            </div>
                        </div>



        </fieldset>

        {% endfor %}
        <br>
        <input type="submit" class="btn btn-primary" value="Register" class="form-check-input">
        <br>
    </form>
    </div>
{% endblock %}

cmm/templates/register_response.html
{% extends "default/base.html" %}

{% block title %}
 {{c.app.app_title + " " + c.app.version_string + " - " + title}}
{% endblock %}

{% block content %}
<div class="jumbotron">
  <div class="d-flex flex.row">
    <div class="d-flex flex.col" style="width:40%;">
      <div>
        <h4>Thank you for your Registration {% if name %}<span class="text-success">{{name}}{% endif %}</span></h4>
      We recorded the following information: <br>
      </div>

    </div>
    <div class="d-flex flex.col">
      <div>
        <h7>Link to your Account: <b>
          <a href="#">{{c.app.site_url + "/" + user_uuid}}</a>
        </b></h7>
        <br>
        Your E-Mail: {{mail}}
        <br>
        Your Selection:

      </div>

    </div>
  </div>


</div>
Shortly you will receive a E-Mail containing further Information and Instructions about how to proceed.
<!--
  {% if name %}
  <h1>thank you for registering {{name}}!</h1>
  {% endif %}
    {% if tags %}
  <h1>{{tags}}!</h1>
  {% endif %}
  <p>please check your mail ({{mail}}) to finish activation</p>
  <p>debug {{user_uuid}}</p>

  -->
{% endblock %}

cmm/templates/root_main.html
{% extends "default/base.html" %}

{% block title %}
 {{c.app.page_title + " " + c.app.version_string + " - " + title}}
{% endblock %}

{% block content %}
<br><br>
<div class="jumbotron">
  <center>
    <img src="{{c.event.logo}}"><br>
    <h1 class="display-4">{{c.app.page_title}}</h1>
    <p class="lead">{{ _('Welcome to the matchmaking software of the Chaosmentors')}}</p>
  <hr class="my-4">
  <p>{{_('Demotext')}}
  </p>
  <a class="btn btn-primary btn-lg" href="{{url_for('user.register')}}" role="button">{{_('Register')}}</a></center>
</div>

{% endblock %}

{% block footer %}
<div class="corner-ribbon top-right sticky red shadow">Pre-Alpha !!</div>
{% endblock %}

cmm/templates/user_profile.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>register</title>
    </head>
 <body>
 {% if user %}
 <p>{{user.name}}</p>
 <p>{{user.tags}}</p>
 <p>{{user.description}}</p>
 {% else %}
 <p>unknown user</p>
 {% endif %}
 </body>
</html>

cmm/templates/user_register.html
{% extends "default/base.html" %}

{% block title %}
 {{c.app.page_title + " " + c.app.version_string + " - " + title}}
{% endblock %}

{% block content %}
<div class="jumbotron">
    <h3>{{_('Please Register as a Mentee')}}</h3>
    <form method="POST" action="{{url_for('user.register_response')}}">

                    <label for="nickname">{{_('Nickname')}}:</label>
                    <input type="text" id="nickname" name="nickname" class="form-control" required>


                    <label for="mail">{{_('Mail')}}:</label>
                    <input type="email" id="mail" name="mail" class="form-control" required>



                    <label for="description">{{_('Description')}}:</label>
                    <textarea
                            rows="5"
                            cols="60"
                            id="description"
                            class="form-control"
                            placeholder="Please give us a brief description of yourself and your interests!">

                    </textarea>


        <br><br>
        <h6>{{_('Please select your Interests')}}:</h6>
        {% for tag in tags: %}
        <fieldset id="{{tag}}">
                        <div class="form-col cmm-border-right">
                            <h7>{{tag}}: </h7>
                        </div>
                        <div class="form-col">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="{{tag}}" id="interested" value="interested" checked="checked" />
                                <label for="interested" class="form-check-label">1</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="{{tag}}" id="maybe" value="maybe"/>
                                <label for="maybe" class="form-check-label">2</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="{{tag}}" id="dislike" value="dislike" />
                                 <label for="dislike" class="form-check-label">3</label>
                            </div>
                        </div>
        </fieldset>

        {% endfor %}
        <br>
        <input type="submit" class="btn btn-primary" value="{{_('Register')}}" class="form-check-input">
        <br>
    </form>
    </div>
{% endblock %}

cmm/templates/user_register_p.html
{% extends "default/base.html" %}

{% block title %}
 {{c.app.page_title + " " + c.app.version_string + " - " + title}}
{% endblock %}

{% block content %}
<div class="jumbotron">
    <h3>{{_('Please Register as a Mentee')}}</h3>
    <form method="POST" action="{{url_for('user.register_response')}}">
        {% for field in form %}
          <p>{{ field.label }} {{ field(class_="form-control") }}</p>
        {% endfor %}


        <br><br>

        <h6>{{_('Please select your Interests')}}:</h6>


        {% for tag in tags: %}
        <fieldset id="{{tag}}">
                        <div class="form-col cmm-border-right">
                            <h7>{{tag}}:</h7>
                        </div>
                        <div class="form-col">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="{{tag}}" id="interested" value="2" checked="checked" />
                                <label for="interested" class="form-check-label">interested</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="{{tag}}" id="maybe" value="1"/>
                                <label for="maybe" class="form-check-label">maybe</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="{{tag}}" id="dislike" value="0" />
                                 <label for="dislike" class="form-check-label">dislike</label>
                            </div>
                        </div>
        </fieldset>

        {% endfor %}
        <br>
        <input type="submit" class="btn btn-primary form-check-input" value="{{_('Register')}}" >
        <br>
    </form>
    </div>
{% endblock %}

cmm/templates/user_register_response.html
{% extends "default/base.html" %}

{% block title %}
 {{c.app.page_title + " " + c.app.version_string + " - " + title}}
{% endblock %}

{% block content %}
<div class="jumbotron">
  <div class="d-flex flex.row">
    <div class="d-flex flex.col" style="width:40%;">
      <div>
        <h4>{{_('Thank you for your Registration')}} {% if user.name %}<span class="text-success">{{user.name}}{% endif %}</span></h4>
      {{_('We recorded the following information')}}: <br>
      </div>

    </div>
    <div class="d-flex flex.col">
      <div>
        <h7>{{_('Link to your Account')}}: <b>
          <a href="#">{{c.app.site_url + "/" + "dsf"}}</a>
        </b></h7>
        <br>
        {{_('Your E-Mail')}}: {{user.email}}
        <br>
        {{_('Your Selection')}}:

      </div>

    </div>
  </div>


</div>
{{_('Shortly you will receive a E-Mail containing further Information and Instructions about how to proceed')}}.
<!--
  {% if name %}
  <h1>thank you for registering {{name}}!</h1>
  {% endif %}
    {% if tags %}
  <h1>{{tags}}!</h1>
  {% endif %}
  <p>please check your mail ({{mail}}) to finish activation</p>
  <p>debug {{user_uuid}}</p>

  -->
{% endblock %}

cmm/templates/users_profile.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>register</title>
    </head>
 <body>
 {% if user %}
 <p>{{user.name}}</p>
 <p>{{user.tags}}</p>
 <p>{{user.description}}</p>
 {% else %}
 <p>unknown user</p>
 {% endif %}
 </body>
</html>

cmm/templates/users_register.html
{% extends "default/base.html" %}

{% block title %}
 {{c.app.page_title + " " + c.app.version_string + " - " + title}}
{% endblock %}

{% block content %}
<div class="jumbotron">
    <h3>{{_('Please Register as a Mentee')}}</h3>
    <form method="POST" action="{{url_for('users.register_response')}}">

                    <label for="nickname">{{_('Nickname')}}:</label>
                    <input type="text" id="nickname" name="nickname" class="form-control" required>


                    <label for="mail">{{_('Mail')}}:</label>
                    <input type="email" id="mail" name="mail" class="form-control" required>



                    <label for="description">{{_('Description')}}:</label>
                    <textarea
                            rows="5"
                            cols="60"
                            id="description"
                            class="form-control"
                            placeholder="Please give us a brief description of yourself and your interests!">

                    </textarea>


        <br><br>
        <h6>{{_('Please select your Interests')}}:</h6>
        {% for tag in tags: %}
        <fieldset id="{{tag}}">



                        <div class="form-col cmm-border-right">
                            <h7>{{tag}}: </h7>
                        </div>
                        <div class="form-col">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="{{tag}}" id="interested" value="interested" checked="checked" />
                                <label for="interested" class="form-check-label">1</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="{{tag}}" id="maybe" value="maybe"/>
                                <label for="maybe" class="form-check-label">2</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="{{tag}}" id="dislike" value="dislike" />
                                 <label for="dislike" class="form-check-label">3</label>
                            </div>
                        </div>



        </fieldset>

        {% endfor %}
        <br>
        <input type="submit" class="btn btn-primary" value="{{_('Register')}}" class="form-check-input">
        <br>
    </form>
    </div>
{% endblock %}

cmm/templates/users_register_response.html
{% extends "default/base.html" %}

{% block title %}
 {{c.app.page_title + " " + c.app.version_string + " - " + title}}
{% endblock %}

{% block content %}
<div class="jumbotron">
  <div class="d-flex flex.row">
    <div class="d-flex flex.col" style="width:40%;">
      <div>
        <h4>{{_('Thank you for your Registration')}} {% if name %}<span class="text-success">{{name}}{% endif %}</span></h4>
      {{_('We recorded the following information')}}: <br>
      </div>

    </div>
    <div class="d-flex flex.col">
      <div>
        <h7>{{_('Link to your Account')}}: <b>
          <a href="#">{{c.app.site_url + "/" + user_uuid}}</a>
        </b></h7>
        <br>
        {{_('Your E-Mail')}}: {{mail}}
        <br>
        {{_('Your Selection')}}:

      </div>

    </div>
  </div>


</div>
{{_('Shortly you will receive a E-Mail containing further Information and Instructions about how to proceed')}}.
<!--
  {% if name %}
  <h1>thank you for registering {{name}}!</h1>
  {% endif %}
    {% if tags %}
  <h1>{{tags}}!</h1>
  {% endif %}
  <p>please check your mail ({{mail}}) to finish activation</p>
  <p>debug {{user_uuid}}</p>

  -->
{% endblock %}